### PR TITLE
Remove what appears to be test code from GUI_login.py

### PR DESCRIPTION
**Pull request by mp15**
[paths] data should come from config_company.ini not be set to C:

### CODE REVIEW

**Comment by bmschoene** [comment]
As these are user-specific and meant to later be changed via the GUI (if needed), these values are only placeholders and should not be deleted. We can leave them empty, though, which should have the same consequence. (They are just the *default* paths used when opening or saving a file.)

**Comment by mp15** [comment]
If I leave them in, I am unable to login to a newly created user because they are copied in automatically from config_company.ini and the file ends up with two ```[Path]``` sections, resulting in a crash.

**Comment by bmschoene** [comment]
That's another one of the bugs that the new release will fix.

**Comment by bmschoene** [comment]
The new release is up.

**Pull request closed without merging**
